### PR TITLE
Cache `precursorMz` values for faster candidate lookup

### PR DESCRIPTION
**Pull request by meowcat**
As discussed in #28

### CODE REVIEW

**Review by jorainer — CHANGES_REQUESTED** [review]
Thanks @meowcat ! Looks great to me! I would only suggest the following minor changes:

- add yourself as a contributor to the *DESCRIPTION*
- increase the version (c part in a.b.c) in *DESCRIPTION*

**Comment by jorainer** [comment]
Ah, and sorry for the long delay!

**Comment by jorainer** [comment]
I'm merging the PR and adding the changes myself. Thanks again @meowcat !

**Comment by meowcat** [comment]
Thanks, and sorry for the delay!

**Pull request merged**
